name: Build Releases
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable

jobs:
  build-release-linux:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: false
      matrix:
        - target: i686-unknown-linux-musl
          features: mimalloc
        - target: x86_64-unknown-linux-gnu
          features: mimalloc
        - target: x86_64-unknown-linux-musl
          features: mimalloc
        - target: armv7-unknown-linux-musleabihf
          features: mimalloc
        - target: armv7-unknown-linux-gnueabihf
          features: mimalloc
        - target: arm-unknown-linux-gnueabi
          features: mimalloc
        - target: arm-unknown-linux-gnueabihf
          features: mimalloc
        - target: arm-unknown-linux-musleabi
          features: mimalloc
        - target: arm-unknown-linux-musleabihf
          features: mimalloc
        - target: aarch64-unknown-linux-gnu
          features: mimalloc
        - target: aarch64-unknown-linux-musl
          features: mimalloc
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: "RUST_TOOLCHAIN=${{env.RUST_TOOLCHAIN}}"

      - name: Install cross
        run: cargo install cross

      - name: Build ${{ matrix.platform.target }}
        timeout-minutes: 120
        run: |
          cross build --release -p rama-cli --target ${{ matrix.platform.target }} --features ${{ matrix.platform.features }}

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/release/*
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ inputs.tag || github.ref_name }}

  build-release-macos:
    runs-on: macos-latest
    env:
      BUILD_EXTRA_FEATURES: "full"
      RUST_BACKTRACE: full
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4

      - name: Install GNU tar
        if: runner.os == 'macOS'
        run: |
          brew install gnu-tar
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: "RUST_TOOLCHAIN=${{env.RUST_TOOLCHAIN}}"

      - name: Build release
        shell: bash
        run: |
          cargo build --release -p rama-cli --target ${{ matrix.platform.target }}

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/release/*
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ inputs.tag || github.ref_name }}

  build-release-windows:
    runs-on: windows-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - i686-pc-windows-gnu
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: "RUST_TOOLCHAIN=${{env.RUST_TOOLCHAIN}}"

      - name: Build release
        run: |
          cargo build --release -p rama-cli --target ${{ matrix.platform.target }}

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/release/*
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ inputs.tag || github.ref_name }}